function fileTypeImageFA(type) {
  const extension = type.toLowerCase();
  switch (extension) {
    // PDF
    case 'pdf':
      return 'fa-file-pdf';
    // Word
    case 'doc':
      return 'fa-file-word';
    case 'docx':
      return 'fa-file-word';
    case 'txt':
      return 'fa-file-word';
    case 'pages':
      return 'fa-file-word';
    // SpreadSheet
    case 'xls':
      return 'fa-file-excel';
    case 'xlsx':
      return 'fa-file-excel';
    case 'xlsm':
      return 'fa-file-excel';
    case 'numbers':
      return 'fa-file-excel';
    case 'numbers-tef':
      return 'fa-file-excel';
    case '123':
      return 'fa-file-excel';
    // Power Point
    case 'ppt':
      return 'fa-file-powerpoint';
    case 'pps':
      return 'fa-file-powerpoint';
    case 'pptx':
      return 'fa-file-powerpoint';
    case 'pptm':
      return 'fa-file-powerpoint';
    case 'potm':
      return 'fa-file-powerpoint';
    case 'ppsx':
      return 'fa-file-powerpoint';
    case 'odp':
      return 'fa-file-powerpoint';
    case 'key':
      return 'fa-file-powerpoint';
    // Images
    case 'tif':
      return 'fa-file-image';
    case 'tiff':
      return 'fa-file-image';
    case 'gif':
      return 'fa-file-image';
    case 'png':
      return 'fa-file-image';
    case 'jpg':
      return 'fa-file-image';
    case 'jpeg':
      return 'fa-file-image';
    case 'bmp':
      return 'fa-file-image';
    case 'eps':
      return 'fa-file-image';
    case 'raw':
      return 'fa-file-image';
    // Links
    case 'link':
      return 'fa-link';
    // Video
    case 'video':
      return 'fa-file-video';
    case 'mp4':
      return 'fa-file-video';
    case 'mpeg-4':
      return 'fa-file-video';
    case 'mkv':
      return 'fa-file-video';
    case 'mov':
      return 'fa-file-video';
    case 'avi':
      return 'fa-file-video';
    case 'wmv':
      return 'fa-file-video';
    case 'webm':
      return 'fa-file-video';
    // Archive
    case 'zip':
      return 'fa-file-archive';
    case 'rar':
      return 'fa-file-archive';
    case 'gz':
      return 'fa-file-archive';
    case 'pkg':
      return 'fa-file-archive';
    case 'deb':
      return 'fa-file-archive';
    case '7z':
      return 'fa-file-archive';
    // Other
    case 'OTHER':
      return 'fa-question';
    default:
      return 'fa-question';
  }
}

export default fileTypeImageFA;
